# ============================================================
#  conditional_mean_functions.py  (Two-fold cross-fitted PPCI, clean sigma^2)
#
#  Key conventions (match paper/demo logic):
#   - w(·): RKHS localization weight function (learned from UNLABELED covariates only)
#   - f(·): predictor (auxiliary ML model output), generated by the DGP
#   - Two-fold cross-fitting is applied ONLY on unlabeled covariates:
#       * train w^(1) on fold I1, tune lambda_1 on I1
#       * train w^(2) on fold I2, tune lambda_2 on I2
#       * unlabeled evaluation uses out-of-fold weights w_oof
#       * labeled evaluation uses averaged weight wbar = 0.5*(w^(1)+w^(2))
#
#  sigma^2 items (theta-aware, consistent with your notation):
#    sigma2_Y_minus_f(theta) = Var( wbar(X) * ( ell(Y;theta)-ell(f;theta) ) )
#    sigma2_f(theta)         = Var( w_oof(X~) * ell(f(X~);theta) )
#    sigma2_Y(theta)         = Var( wbar(X) * ell(Y;theta) )      [label-only baseline]
#
#  Mean loss: ell(v;theta) = v - theta
#    => ell(Y;theta)-ell(f;theta) = Y - f  (theta cancels)
# ============================================================

import numpy as np
import cupy as cp
import matplotlib.pyplot as plt

xp = cp


# ============================================================
# 0) Optional X preprocessing: standardize (CPU)
#    (Use only if you really want; for X~Unif([0,1]^d), identity is fine.)
# ============================================================
def preprocess_X(X_total):
    X_total = np.asarray(X_total, dtype=float)
    mean = X_total.mean(axis=0)
    std = X_total.std(axis=0)
    std[std == 0.0] = 1.0
    X_scaled = (X_total - mean) / std
    return X_scaled, mean, std


# ============================================================
# 1) Matérn kernel ν=2.5 (Matérn 5/2) matrix
# ============================================================
def K_matern52_matrix(X, Z, ell):
    X = xp.asarray(X)
    Z = xp.asarray(Z)
    ell = float(ell)

    X2 = xp.sum(X**2, axis=1, keepdims=True)
    Z2 = xp.sum(Z**2, axis=1, keepdims=True).T
    d2 = X2 + Z2 - 2.0 * (X @ Z.T)
    d2 = xp.maximum(d2, 0.0)
    r = xp.sqrt(d2 + 1e-18)

    sqrt5 = np.sqrt(5.0)
    t = (sqrt5 * r) / (ell + 1e-18)
    poly = 1.0 + t + (t**2) / 3.0
    return poly * xp.exp(-t)


# ============================================================
# 2) Pilot ell selection: LOGO-CV (with unique groups => LOOCV)
# ============================================================
def make_age_groups(age_raw, bin_width=1):
    age_raw = np.asarray(age_raw, dtype=float)
    if bin_width <= 1:
        return age_raw.astype(int)
    return (np.floor(age_raw / bin_width) * bin_width).astype(int)
    
def nw_logo_cv_mse_matern52(X, Y, group_labels, ell, min_train=5):
    X = xp.asarray(X)
    Y = xp.asarray(Y).ravel()
    group_labels = np.asarray(group_labels)

    n = int(Y.size)
    if n <= 2:
        return np.inf

    K = K_matern52_matrix(X, X, ell)  # (n, n)

    uniq = np.unique(group_labels)
    se_sum_total = 0.0
    n_total = 0

    for g in uniq:
        te = np.where(group_labels == g)[0]
        if te.size == 0:
            continue
        tr = np.where(group_labels != g)[0]
        if tr.size < min_train:
            continue

        te_gpu = cp.asarray(te, dtype=cp.int32)
        tr_gpu = cp.asarray(tr, dtype=cp.int32)

        K_te_tr = K[te_gpu][:, tr_gpu]
        den = xp.sum(K_te_tr, axis=1)
        den = xp.maximum(den, 1e-12)

        Y_tr = Y[tr_gpu]
        pred = (K_te_tr @ Y_tr) / den

        resid = Y[te_gpu] - pred
        se_sum_total += float(xp.sum(resid**2))
        n_total += int(te.size)

    if n_total == 0:
        return np.inf
    return se_sum_total / n_total


def select_logell_by_pilot_logo_cv(LOGELL_grid, X_pilot, Y_pilot, group_labels):
    records = []
    for logell in LOGELL_grid:
        logell_val = float(logell)
        ell_val = float(np.exp(logell_val))
        cv_mse = nw_logo_cv_mse_matern52(
            X=X_pilot, Y=Y_pilot, group_labels=group_labels, ell=ell_val
        )
        records.append({"logell": logell_val, "ell": ell_val, "cv_mse": cv_mse})

    scores = np.array([r["cv_mse"] for r in records], dtype=float)
    best_idx = int(np.argmin(scores))
    ell_star = float(records[best_idx]["ell"])
    return ell_star, records


# ============================================================
# 3) Mean loss / score
# ============================================================
# ============================================================
# 3) NW point estimator (only to define theta0_smooth)
# ============================================================
def nw_point_mean_ci_matern52(X_l, Y_l, x0, ell, z_alpha=1.96):
    X_l = xp.asarray(X_l)
    Y_l = xp.asarray(Y_l).ravel()
    x0_gpu = xp.asarray(x0).ravel()

    k = K_matern52_matrix(x0_gpu.reshape(1, -1), X_l, ell).ravel()
    ksum = float(xp.sum(k))

    if abs(ksum) <= 1e-16:
        d2 = xp.sum((X_l - x0_gpu) ** 2, axis=1)
        idx = int(xp.argmin(d2))
        theta_hat = float(Y_l[idx])
        return theta_hat, 0.0, (theta_hat, theta_hat)

    w = k / (ksum + 1e-16)
    theta_hat = float(w @ Y_l)

    var_hat = float(xp.sum((w**2) * (Y_l - theta_hat) ** 2))
    var_hat = max(var_hat, 0.0)
    se = float(np.sqrt(var_hat))
    return theta_hat, se, (theta_hat - z_alpha * se, theta_hat + z_alpha * se)
def ell_mean(v, theta):
    v = xp.asarray(v).ravel()
    return v - float(theta)


# ============================================================
# 4) WeightAtX0: build w_hat(·) = sum_u K(·, X_u) alpha_u
#    + L-curve lambda selection (already uses eigendecomp)
# ============================================================
class WeightAtX0:
    def __init__(self, X_fold, x0, ell):
        """
        X_fold: unlabeled covariates in ONE fold (GPU array), shape (N_fold, d)
        x0: test point (same scale as X_fold), shape (d,)
        ell: kernel length-scale
        """
        self.X_fold = xp.asarray(X_fold)
        self.ell = float(ell)
        self.N_fold = int(self.X_fold.shape[0])

        K_ff = K_matern52_matrix(self.X_fold, self.X_fold, self.ell)
        K_ff = 0.5 * (K_ff + K_ff.T)

        eigvals, eigvecs = xp.linalg.eigh(K_ff)
        self.eigvals = xp.maximum(eigvals, 1e-12)
        self.eigvecs = eigvecs

        x0_gpu = xp.asarray(x0).reshape(1, -1)
        k_x0 = K_matern52_matrix(self.X_fold, x0_gpu, self.ell)[:, 0]
        self.tmp_x0 = self.eigvecs.T @ k_x0  # Q^T k_x0

    def alpha(self, lam: float):
        denom = self.eigvals + self.N_fold * float(lam)
        return self.eigvecs @ (self.tmp_x0 / denom)

    def select_lambda_lcurve(self, lam_grid, normalize=False, make_plot=False):
        lam_grid = np.asarray(lam_grid, dtype=float)
        lam_grid = np.sort(lam_grid)
        if lam_grid.size == 0:
            raise ValueError("lam_grid is empty.")

        tmp = self.tmp_x0
        eigvals = self.eigvals
        Nf = self.N_fold

        bias_log_raw, ef2_log_raw = [], []

        for lam in lam_grid:
            lam_val = float(lam)
            denom = eigvals + Nf * lam_val

            ratio = (Nf * lam_val) / denom
            resid_sq = float(xp.sum((ratio * tmp) ** 2))

            k_alpha = eigvals * (tmp / denom)
            ef2 = float(xp.sum(k_alpha**2)) / max(Nf, 1)

            bias_log_raw.append(np.log(resid_sq + 1e-30))
            ef2_log_raw.append(np.log(ef2 + 1e-30))

        bias_log_raw = np.asarray(bias_log_raw)
        ef2_log_raw = np.asarray(ef2_log_raw)

        x = bias_log_raw.copy()
        y = ef2_log_raw.copy()

        if normalize:
            x = (x - x.min()) / (x.max() - x.min() + 1e-16)
            y = (y - y.min()) / (y.max() - y.min() + 1e-16)

        p_start = np.array([x[0], y[0]])
        p_end = np.array([x[-1], y[-1]])
        vec_line = p_end - p_start
        line_norm = np.linalg.norm(vec_line) + 1e-12

        dists = []
        for xi, yi in zip(x, y):
            vec_p = np.array([xi, yi]) - p_start
            cross = vec_p[0] * vec_line[1] - vec_p[1] * vec_line[0]
            dists.append(abs(cross) / line_norm)

        dist_curve = np.asarray(dists, dtype=float)
        best_idx = int(np.argmax(dist_curve))
        best_lam = float(lam_grid[best_idx])

        if make_plot:
            fig = plt.figure(figsize=(15, 5))
            ax1 = fig.add_subplot(131)
            ax1.plot(bias_log_raw, ef2_log_raw, lw=2, alpha=0.8)
            ax1.scatter(bias_log_raw[best_idx], ef2_log_raw[best_idx], s=150, marker="*", zorder=10)
            ax1.set_xlabel("Log Bias Proxy")
            ax1.set_ylabel(r"Log Empirical $E[\hat w^2]$")
            ax1.grid(True, alpha=0.3)

            ax2 = fig.add_subplot(132)
            ax2.plot(np.log10(lam_grid), dist_curve, lw=2)
            ax2.axvline(np.log10(best_lam), ls="--")
            ax2.set_xlabel(r"$\log_{10}(\lambda)$")
            ax2.set_ylabel("Geometric Distance")
            ax2.grid(True, alpha=0.3)

            plt.tight_layout()
            plt.show()

        alpha_hat = self.alpha(best_lam)
        return best_lam, alpha_hat, lam_grid

    def make_w_hat(self, alpha_hat):
        """
        Return a callable w_hat(X_query) that outputs weights at query points.
        """
        X_fold = self.X_fold
        ell = self.ell
        alpha_hat = xp.asarray(alpha_hat)

        def w_hat(X_query):
            X_query = xp.asarray(X_query)
            return K_matern52_matrix(X_query, X_fold, ell) @ alpha_hat

        return w_hat


# ============================================================
# 5) Two-fold weight builder (unlabeled cross-fitting ONLY)
# ============================================================
def build_twofold_weights(
    X_u, x0, ell, lam_grid, idx_fold1, idx_fold2, make_plot=False
):
    """
    Inputs:
      X_u: unlabeled covariates (GPU), shape (N, d)
      idx_fold1, idx_fold2: numpy integer arrays forming a partition of {0,...,N-1}
    Outputs:
      w1_hat, w2_hat: callables for fold-specific weights
      w_oof_u: out-of-fold weights evaluated on ALL unlabeled points, shape (N,)
      den_u: mean(w_oof_u)
      lam1, lam2: tuned lambdas for each fold
    """
    X_u = xp.asarray(X_u)
    x0 = np.asarray(x0, dtype=float).ravel()

    idx_fold1 = np.asarray(idx_fold1, dtype=int)
    idx_fold2 = np.asarray(idx_fold2, dtype=int)

    X1 = X_u[cp.asarray(idx_fold1, dtype=cp.int32)]
    X2 = X_u[cp.asarray(idx_fold2, dtype=cp.int32)]

    # Train / tune on fold1
    loc1 = WeightAtX0(X_fold=X1, x0=x0, ell=ell)
    lam1, alpha1, _ = loc1.select_lambda_lcurve(lam_grid=lam_grid, make_plot=make_plot)
    w1_hat = loc1.make_w_hat(alpha1)

    # Train / tune on fold2
    loc2 = WeightAtX0(X_fold=X2, x0=x0, ell=ell)
    lam2, alpha2, _ = loc2.select_lambda_lcurve(lam_grid=lam_grid, make_plot=make_plot)
    w2_hat = loc2.make_w_hat(alpha2)

    # Out-of-fold weights on unlabeled points
    N = int(X_u.shape[0])
    w_oof = xp.zeros((N,), dtype=X_u.dtype)

    # For u in fold1 => evaluate using w2_hat (trained on fold2)
    w_oof[cp.asarray(idx_fold1, dtype=cp.int32)] = w2_hat(X_u[cp.asarray(idx_fold1, dtype=cp.int32)]).ravel()
    # For u in fold2 => evaluate using w1_hat (trained on fold1)
    w_oof[cp.asarray(idx_fold2, dtype=cp.int32)] = w1_hat(X_u[cp.asarray(idx_fold2, dtype=cp.int32)]).ravel()

    den_u = float(xp.mean(w_oof))
    return w1_hat, w2_hat, w_oof, den_u, lam1, lam2


# ============================================================
# 6) PPCI conditional mean (two-fold CF weights) + CI + sigma^2
# ============================================================
def ppci_conditional_mean_cf(
    X_l, Y_l, f_l, f_u,
    w1_hat, w2_hat, w_oof_u,
    z_alpha=1.96, return_extras=True, theta_for_var=None
):
    """
    Conditional mean target at x0:
      theta0(x0) = E[Y | X=x0]

    PPCI (mean case, with cross-fitted weights on unlabeled only):
      theta_hat = ( mean_l[ wbar(X)*(Y - f(X)) ] + mean_u[ w_oof(X~)*f(X~) ] ) / mean_u[w_oof(X~)]

    where:
      wbar(X) = 0.5*(w1_hat(X) + w2_hat(X))
      w_oof_u are the out-of-fold weights evaluated on the unlabeled covariates.

    CI uses the same influence-style plug-in form as your previous implementation.
    """
    X_l = xp.asarray(X_l)
    Y_l = xp.asarray(Y_l).ravel()
    f_l = xp.asarray(f_l).ravel()
    f_u = xp.asarray(f_u).ravel()
    w_oof_u = xp.asarray(w_oof_u).ravel()

    n = int(X_l.shape[0])
    N = int(f_u.size)
    Np = n + N

    # Labeled weights (average of two fold-trained weight functions)
    wbar_l = 0.5 * (w1_hat(X_l).ravel() + w2_hat(X_l).ravel())

    den = xp.mean(w_oof_u)
    num = xp.mean(wbar_l * (Y_l - f_l)) + xp.mean(w_oof_u * f_u)
    theta_hat = float(num / (den + 1e-16))

    theta_var = theta_hat if (theta_for_var is None) else float(theta_for_var)

    # ---- sigma^2 items ----
    g_Ymf = wbar_l * (Y_l - f_l)  # = wbar*(ell(Y;θ)-ell(f;θ)) for mean
    sigma2_Y_minus_f = float(xp.var(g_Ymf, ddof=1)) if n > 1 else 0.0

    g_f = w_oof_u * ell_mean(f_u, theta_var)  # = w_oof*ell(f;θ)
    sigma2_f = float(xp.var(g_f, ddof=1)) if N > 1 else 0.0

    # ---- CI (same influence-style structure) ----
    psi_R = g_Ymf
    psi_U = w_oof_u * (f_u - theta_hat)  # linearization uses theta_hat

    var_R = float(xp.var(psi_R, ddof=1)) if n > 1 else 0.0
    var_U = float(xp.var(psi_U, ddof=1)) if N > 1 else 0.0

    p_R = n / max(Np, 1)
    p_U = N / max(Np, 1)

    Sigma_hat = (var_R / max(p_R, 1e-12)) + (var_U / max(p_U, 1e-12))

    H_hat = float(-den)
    V_hat = Sigma_hat / ((H_hat + 1e-16) ** 2)
    se = float(np.sqrt(max(V_hat, 0.0) / max(Np, 1)))

    ci = (theta_hat - z_alpha * se, theta_hat + z_alpha * se)

    if not return_extras:
        return theta_hat, se, ci

    extras = {
        "n": n,
        "N": N,
        "N_prime": Np,
        "den_u": float(den),
        "H_hat": float(H_hat),
        "Sigma_hat": float(Sigma_hat),
        "V_hat": float(V_hat),
        "theta_for_var": float(theta_var),
        "sigma2_Y_minus_f": float(sigma2_Y_minus_f),
        "sigma2_f": float(sigma2_f),
        "var_R": float(var_R),
        "var_U": float(var_U),
    }
    return theta_hat, se, ci, extras


# ============================================================
# 7) Label-only baseline (LO): uses wbar(X) only
# ============================================================
def ppci_conditional_mean_label_only_cf(
    X_l, Y_l, w1_hat, w2_hat,
    z_alpha=1.96, return_extras=True, theta_for_var=None, denom_floor=1e-10
):
    """
    LO baseline (conditional, no predictor f):
      theta_hat = sum_i wbar(X_i) Y_i / sum_i wbar(X_i),
      wbar(X) = 0.5*(w1_hat(X)+w2_hat(X)).

    Includes denominator stabilization to avoid numerical blow-ups.
    """
    X_l = xp.asarray(X_l)
    Y_l = xp.asarray(Y_l).ravel()
    n = int(Y_l.size)

    wbar_l = 0.5 * (w1_hat(X_l).ravel() + w2_hat(X_l).ravel())
    denom = float(xp.sum(wbar_l))
    denom_safe = max(denom, float(denom_floor))

    theta_hat = float((wbar_l @ Y_l) / (denom_safe + 1e-16))

    # simple weighted variance (same style as your previous LO)
    w_norm = wbar_l / (denom_safe + 1e-16)
    var_hat = float(xp.sum((w_norm**2) * (Y_l - theta_hat) ** 2))
    var_hat = max(var_hat, 0.0)
    se = float(np.sqrt(var_hat))
    ci = (theta_hat - z_alpha * se, theta_hat + z_alpha * se)

    theta_var = theta_hat if (theta_for_var is None) else float(theta_for_var)
    gY = wbar_l * ell_mean(Y_l, theta_var)
    sigma2_Y = float(xp.var(gY, ddof=1)) if n > 1 else 0.0

    if not return_extras:
        return theta_hat, se, ci

    extras = {
        "n": n,
        "denom_sumw": float(denom),
        "denom_safe": float(denom_safe),
        "theta_for_var": float(theta_var),
        "sigma2_Y": float(sigma2_Y),
        "var_weighted": float(var_hat),
    }
    return theta_hat, se, ci, extras